/**
 * Phase A 検証用: pattern slug 統一に伴う redirect とリネーム結果のスモーク検査。
 *
 * 前提: `npm run build` を実行済みで dist/ に出力がある。
 * 用途: Phase A の PR 検証のみの一時スクリプト。リリース後に削除して差し支えない。
 *
 * 実行: `npx tsx scripts/check-redirects.ts`
 *   - 環境変数 BASE_PATH (デフォルト '/apg-patterns-examples')
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const DIST = 'dist';
const BASE = process.env.BASE_PATH ?? '/apg-patterns-examples';

const pairs: Array<[string, string]> = [
  ['radio-group', 'radio'],
  ['tree-view', 'treeview'],
  ['window-splitter', 'windowsplitter'],
];
const frameworks = ['react', 'vue', 'svelte', 'astro'];
const locales = ['', 'ja/'];

let checked = 0;
let errors = 0;

function fail(msg: string) {
  console.error(`  ✗ ${msg}`);
  errors++;
}

function checkRedirect(htmlPath: string, expectedUrl: string) {
  checked++;
  if (!existsSync(htmlPath)) {
    fail(`old URL HTML missing: ${htmlPath}`);
    return;
  }
  const html = readFileSync(htmlPath, 'utf-8');
  if (!html.includes(`url=${expectedUrl}`)) {
    fail(`wrong refresh URL in ${htmlPath} (expected: ${expectedUrl})`);
  }
}

function checkNewPageExists(htmlPath: string, opts: { isBase?: boolean; slug?: string } = {}) {
  checked++;
  if (!existsSync(htmlPath)) {
    fail(`new URL HTML missing: ${htmlPath}`);
    return;
  }
  const html = readFileSync(htmlPath, 'utf-8');
  // Astro redirects config 由来の meta refresh ページは noindex robots meta を含む。
  // 動的ルート src/pages/patterns/[pattern]/index.astro の JS redirect ページ
  // (新 URL の base) は含まないので、これで両者を区別する。
  if (html.includes('content="noindex"')) {
    fail(`new URL was generated by redirects config (unexpected): ${htmlPath}`);
    return;
  }
  if (opts.isBase && opts.slug && !html.includes(`data-pattern="${opts.slug}"`)) {
    fail(`new base page missing data-pattern="${opts.slug}": ${htmlPath}`);
  }
}

console.log(`Checking redirects in ${DIST}/ (base: ${BASE})\n`);

for (const [oldSlug, newSlug] of pairs) {
  for (const locale of locales) {
    // 旧 URL (base + framework + demo) → meta refresh は新 URL へ
    checkRedirect(
      join(DIST, locale, 'patterns', oldSlug, 'index.html'),
      `${BASE}/${locale}patterns/${newSlug}`
    );
    for (const fw of frameworks) {
      checkRedirect(
        join(DIST, locale, 'patterns', oldSlug, fw, 'index.html'),
        `${BASE}/${locale}patterns/${newSlug}/${fw}`
      );
      checkRedirect(
        join(DIST, locale, 'patterns', oldSlug, fw, 'demo', 'index.html'),
        `${BASE}/${locale}patterns/${newSlug}/${fw}/demo`
      );
    }

    // 新 URL は実体ページ (redirects config 由来でないこと)
    checkNewPageExists(join(DIST, locale, 'patterns', newSlug, 'index.html'), {
      isBase: true,
      slug: newSlug,
    });
    for (const fw of frameworks) {
      checkNewPageExists(join(DIST, locale, 'patterns', newSlug, fw, 'index.html'));
      checkNewPageExists(join(DIST, locale, 'patterns', newSlug, fw, 'demo', 'index.html'));
    }
  }
}

console.log(`\nChecked ${checked} URLs, ${errors} error(s).`);
if (errors > 0) process.exit(1);
